### ISSUE TITLE
Error on trying to use in a new build.gradle

### ISSUE THREAD

**Issue by wgaylord** [nailed/mcp#8]
I am getting http://pastebin.com/2e5aBy9z when trying to run gradle tasks 

This is using an exact copy http://pastebin.com/bxTniaSG as my build.gradle  

The strange thing is that with a project that has the same build.gradle with only the mappings field and also the group field changed works with out problem.

**Comment by wgaylord** [comment]
I really need this for my latest project.

**Comment by wgaylord** [comment]
Okay I figured out the problem. You have to have a subproject that is named api. Which does not seem right but okay.. I will just close this I guess.

**Comment by jeffreykog** [comment]
Excuse me for the delay. I was going to contact you on IRC but i was really busy the last few days.
As you may or may not know, nailed MCP is designed for nailed, so it has some project things hardcoded, like the api subproject.
I really appreciate you using my work and reporting issues if something is wrong. At the time, nailed mcp was the only gradle plugin that was able to decompile and reobfuscate vanilla minecraft server.
Now since the release of ForgeGradle 2.0 this project became obsolete because FG now natively supports the vanilla server instead of a forge server.
I suggest you take a look at the ForgeGradle 2.0 TweakerServer plugin. If you need help with that, i'm more than happy to help you move over to it and make everything work perfectly.

**Comment by wgaylord** [comment]
Okay. Yeah. I will see if I can figure out FG2.

**Comment by jeffreykog** [comment]
Again, if you need help figuring out how it works you can always poke me on
irc. Good luck :)
